# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       mce-headers

# >> macros
# << macros

Summary:    Development files for mce
Version:    1.13.0
Release:    1
Group:      Development/Libraries
License:    LGPLv2
URL:        https://github.com/nemomobile/mce-dev
Source0:    %{name}-%{version}.tar.bz2
Source100:  mce-headers.yaml
Patch0:     %{name}-1.10.24-no-ownership.patch
BuildRequires:  doxygen

%description
This package contains headers defining the D-Bus method calls
provided by the Mode Control Entity, and the signals emitted by it.


%package -n mce-doc
Summary:    Documentation files for mce D-Bus API
Group:      Documentation
BuildArch:  noarch

%description -n mce-doc
This package contains documentation describing the D-Bus method calls
provided by the Mode Control Entity, and the signals emitted by it.


%prep
%setup -q -n %{name}-%{version}

# %{name}-1.10.24-no-ownership.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
make doc
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
install -d %{buildroot}/%{_docdir}/mce-doc/html/
install -m 644 doc/html/* %{buildroot}/%{_docdir}/mce-doc/html/
# << install post

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING debian/copyright
%{_includedir}/mce/*.h
%{_libdir}/pkgconfig/mce.pc
# << files

%files -n mce-doc
%defattr(-,root,root,-)
# >> files mce-doc
%doc COPYING debian/changelog debian/copyright
%{_docdir}/mce-doc/html/*
# << files mce-doc
